### ISSUE TITLE
Form Toetsplan

### ISSUE THREAD

**Issue by PkertNL** [PkertNL/ELLMI#6]
Form Toetsplan

Toets-en beoordelingvormen
Vorm -> dropdown (inclusief optie overige om een nieuwe optie toe te voegen)
Beoordelaar -> vrije tekst
Weging -> gehele getallen (dus met regex checken oid & alle wegingen moeten altijd 100 zijn)

Toetsvoorwaarde -> vrije tekst

Bonuspuntenregeling -> vrije tekst

Instrumenten -> vrije tekst

Feedback

Summatief -> vrije tekst (als ze meer dan eentje toe willen voegen met JS zorgen dat er een nieuwe invoer verschijnt)
Formatief -> zie summatief
Overig -> zie summatief

Aandachtspunten -> zie summatief

Toetsschema

Leerdoelen -> dropdown met alle leerdoelen van de module
Toetsvormen -> dropdown met de vormen die boven bij vorm zijn gekozen (meerdere opties mogelijk)

**Comment by eswestra** [comment]
Af!
[toetsplanForm.zip](https://github.com/PkertNL/ELLMI/files/314598/toetsplanForm.zip)
